name: Microservices Security CI (Snyk)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - Authentication-8083
          - Gateway-9090
          - Order-8082
          - Payment-8081
          - Product-8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-v2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v2

      - name: Build parent + all modules
        run: >
          mvn -B -U clean install -DskipTests 
          -Dhttp.keepAlive=false 
          -Dmaven.wagon.http.pool=false 
          -Dmaven.wagon.http.retryHandler.count=3

      - name: Install Snyk & Snyk-to-Html
        run: |
          npm install -g snyk snyk-to-html
          snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Security Scan
        run: |
          echo "Scanning ${{ matrix.service }}..."
          snyk test --file=${{ matrix.service }}/pom.xml --json | snyk-to-html -o snyk-report-${{ matrix.service }}.html || true

      - name: Upload Snyk Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report-${{ matrix.service }}
          path: snyk-report-${{ matrix.service }}.html