name: Microservices Security CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - Authentication-8083
          - Gateway-9090
          - Order-8082
          - Payment-8081
          - Product-8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build parent + all modules
        run: mvn -B -q clean install

      - name: Build microservice
        working-directory: ${{ matrix.service }}
        run: mvn -B clean verify


      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        with:
          project: ${{ matrix.service }}
          path: ${{ matrix.service }}
          format: "HTML"
          out: "reports-${{ matrix.service }}"
          arguments: "--noupdate"

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: "dependency-check-${{ matrix.service }}"
          path: "reports-${{ matrix.service }}/"
