name: Microservices DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true


  build-and-security-scan:
    needs: secret-scan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - Authentication-8083
          - Gateway-9090
          - Order-8082
          - Payment-8081
          - Product-8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-v2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v2

      - name: Build parent + all modules
        run: >
          mvn -B -U clean install -DskipTests 
          -Dhttp.keepAlive=false 
          -Dmaven.wagon.http.pool=false 
          -Dmaven.wagon.http.retryHandler.count=3

      - name: Install Snyk & Snyk-to-Html
        run: |
          npm install -g snyk snyk-to-html
          snyk auth ${{ secrets.SNYK_TOKEN }}


      - name: Run SCA (Dependency Scan)
        run: |
          echo "Running SCA on ${{ matrix.service }}..."
          # || true prevents the build from stopping, allowing SAST to run next
          snyk test --file=${{ matrix.service }}/pom.xml --json | snyk-to-html -o sca-report-${{ matrix.service }}.html || true


      - name: Run SAST (Code Scan)
        run: |
          echo "Running SAST on ${{ matrix.service }}..."
          # Snyk Code analyzes the source code folder
          snyk code test ${{ matrix.service }} --json | snyk-to-html -o sast-report-${{ matrix.service }}.html || true

      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports-${{ matrix.service }}
          path: |
            sca-report-${{ matrix.service }}.html
            sast-report-${{ matrix.service }}.html